### ISSUE TITLE
Unusual loss trend and 'OSError: [WinError 6] The handle is invalid' issue

### ISSUE THREAD

**Issue by Nutty233** [lightly-ai/lightly#1428] opened 2023-11-17 12:57 UTC
Thank you for supporting these codes for our single GPU users.

I'm trying to train VGG 16 using my own dataset (28,685 * (224*224*4band) satellite data) for semantic segmentation with Moco V2.

To fit the number of bands of the images, I changed the PIL image open code from ("RGB") to ("RGBA") from other '.py' files in the 'lightly' package, and set the dynamically reducing learning rate to start with 0.01 (I tried 0.06 0.03, and the loss won't converge). Then I employed the VGG16 framework and changed the parameters of 'MoCoProjectionHead' to (25088, 512, 128) (Maybe I got things wrong here) to let the model work. 

But the loss will always decrease slowly and stuck at about 7.9. (as shown in the attached figure) When the lr dynamically decreases, the loss will increase, then come up with an 'OSError: [WinError 6] The handle is invalid' linked with 'queues.py' and 'connection.py' lately, and the training will end there.
![moco_v2_train_loss](https://github.com/lightly-ai/lightly/assets/89444595/a7a61a6b-4b5a-4622-84a8-b60080179fd8)

Does anyone have any ideas or experience on this? I would appreciate it.

**Comment by guarin** [comment] 2023-11-17 13:36
Hi! Thanks for using lightly!

I never tried training a MoCo model with 4 channels but I would check the following things:
* Make sure your image transforms are working as expected, especially image normalization
* 25088 dimensions in the MoCoProjectionHead sounds like too much. VGG16 usually has 4096 output dimensions, maybe check that the pooling layer works as expected.
* `'OSError: [WinError 6] The handle is invalid'` sounds like an issue with filehandles (too many images opened at the same time). Make sure that images are correctly opened and maybe increase the number of open filehandles limit if necessary.

Hope this helps :)

**Comment by Nutty233** [comment] 2023-11-20 09:54
Thank you for your suggestions! Really helpful.
The problem with "OSError: [WinError 6] Invalid handle" still exists, but setting num_workers = 0 seems to work. After the model is working well, I will try to adjust the code again to use multiprocessing.
I tried to make it feasible to change the input to 4096 for the moco model by changing the frame, and am now adjusting the hyperparameters to let the loss decrease.
Thanks again for giving me a solution idea!

**Comment by guarin** [comment] 2023-12-08 14:32
Closing this issue for now, please reopen if you encounter more errors.

**Closed by guarin** 2023-12-08 14:32 UTC

**Comment by theoVag** [comment] 2024-03-01 18:11
Hello, i am using the VicReg for medical image self-supervision and i noticed the same behavior in the loss function. Loss reduces from 8 to 7.5 and becomes stable. I tried different setting and the behavior was the same. Did you find the problem with the loss values? is there any suggestions about the reasons behind this?

**Comment by guarin** [comment] 2024-03-04 08:10
Hi, the loss curves should look like this:

### MoCoV2
![mocov2](https://github.com/lightly-ai/lightly/assets/43336610/803b24aa-9238-47e7-a915-888f2397c5cf)

### VicReg
![vicreg](https://github.com/lightly-ai/lightly/assets/43336610/5a0f2a05-abf0-4e4b-a497-53857755ec4f)

### Dino
![dino](https://github.com/lightly-ai/lightly/assets/43336610/fafbf139-bad1-4074-b48b-c563240ea103)

The curves are from running our benchmarks here: https://github.com/lightly-ai/lightly/tree/master/benchmarks/imagenet/resnet50

Did you follow the benchmark scripts or the examples in the docs when implementing the model? The examples in the docs are a bit simplified to quicly run on a single, small GPU, whereas the benchmark scripts are full reproductions of the original code with all the training tricks.
