### ISSUE TITLE
Add PIRL 

### ISSUE THREAD

**Issue by ramdhan1989** [lightly-ai/lightly#396] opened 2021-06-04 02:51 UTC
Is there any plan to add PIRL ?

**Comment by philippmwirth** [comment] 2021-06-04 14:11
Yes, we'd like to add PIRL to the framework. However, I can't provide a timeline on this since we're currently planning to do a refactoring of the existing models.

Would you be interested in working on PIRL yourself? It would be a great addition to lightly :)

**Comment by ramdhan1989** [comment] 2021-06-25 15:04
yeah, I would be happy to help.

**Comment by philippmwirth** [comment] 2021-06-28 07:59
Cool! I think a good first step would be to add the "jigsaw" augmentation to [`lightly.transforms`](https://github.com/lightly-ai/lightly/tree/master/lightly/transforms).

If you need any information on how to contribute, please take a look at our [contribution guide](https://github.com/lightly-ai/lightly/blob/master/CONTRIBUTING.md).

The reference paper is [here](https://arxiv.org/pdf/1912.01991.pdf).

Let me know if you there are any questions, I'm happy to help :)

**Comment by shikharmn** [comment] 2021-08-25 14:10
I'm not sure if this issue is still resolved. If not, can this be assigned to me? I'd love to work on this.

**Comment by philippmwirth** [comment] 2021-08-25 15:05
Hi @shikharmn, the issue is not resolved. You're very welcome to work on it. Can I assign the issue to you?

**Comment by shikharmn** [comment] 2021-08-30 04:04
Apologies for the delay, do check out #477 and let me know if any changes are needed.

**Comment by philippmwirth** [comment] 2021-09-24 07:46
Hi @shikharmn and thanks a lot for your contribution! I think the next step would be to write a collate function for PIRL (see [other collate functions](https://github.com/lightly-ai/lightly/blob/master/lightly/data/collate.py) for inspiration).

**Comment by shikharmn** [comment] 2021-09-24 12:21
Okay, sure! I'll start with that and get back to you if I face any issues.

**Comment by shikharmn** [comment] 2022-06-21 21:05
Hi @philippmwirth, is this still relevant? Can pick this up again now.

(sorry, was drowned with uni work)

**Comment by philippmwirth** [comment] 2022-06-22 07:56
Yes sure, I think we can move ahead with this one 👍

**Comment by shikharmn** [comment] 2022-06-24 12:18
Hi @philippmwirth, do let me know if #850 is okay.

**Comment by shikharmn** [comment] 2022-06-24 12:27
Ah no worries, I didn't know if the notification reached you, do take a look whenever you find the time! :)

**Comment by shikharmn** [comment] 2022-06-27 07:32
Thank you @guarin for approving the PR #850! I'll move on to writing the PIRL network and related loss function now to finish this up. Do let me know if there's any details regarding that task which I should keep in mind.

**Comment by philippmwirth** [comment] 2022-06-27 07:34
Awesome work @shikharmn! Looking forward to your future contributions 🙂

**Comment by guarin** [comment] 2024-08-16 09:09
PIRL is now outdated with respect to modern SSL methods and we don't plan on adding it anymore.

**Closed by guarin** 2024-08-16 09:09 UTC
Labels: type: feature, type: idea
