### ISSUE TITLE
complex metadata: allow to upload complex metadata

### ISSUE THREAD

**Issue by japrescott** [lightly-ai/lightly#434] opened 2021-07-05 14:14 UTC
it would be great if I can upload metadata to a sample. By metadata I mean special information I might have about my sample as e.g GPS position, weather condition, driver name, camera sensor or datetime

This could allow me to get more insights in to the data we have at hand by plotting them

**Comment by philippmwirth** [comment] 2021-07-21 05:31
Duplicate of #441 (or the other way around).

**Closed by philippmwirth** 2021-07-21 05:31 UTC
