### ISSUE TITLE
Add DINOv2 method

### ISSUE THREAD

**Issue by whut265107** [lightly-ai/lightly#1686] opened 2024-10-09 03:18 UTC
I find KoLeoLoss of  dinov2  in the doc  ，would you consider adding the dinov2 method to this repository?

**Comment by philippmwirth** [comment] 2024-10-09 06:31
Hi @whut265107, work on DINOv2 is in progress, you can see the current status of all planned self-supervised learning methods in the tracker issue: https://github.com/lightly-ai/lightly/issues/1172. AFAIK all the necessary modules are implemented. What's missing are examples and benchmarks.

I will close this issue as duplicate of https://github.com/lightly-ai/lightly/issues/1166. Please discuss any other questions there, thank you 🙂

**Closed by philippmwirth** 2024-10-09 06:31 UTC
