### ISSUE TITLE
Loss stuck

### ISSUE THREAD

**Issue by Reasat** [lightly-ai/lightly#1007] opened 2022-12-13 21:25 UTC
Hi, I am trying to run the tutorial posted here 
https://docs.lightly.ai/self-supervised-learning/tutorials/package/tutorial_moco_memory_bank.html
But my loss is stuck at 8.32 after 100 epochs
python 3.9
pytorch-lightning 1.8.1 
lightly 1.2.38

Any suggestions on how I should troubleshoot this?
Thanks in advance!

**Comment by AurelienGauffre** [comment] 2022-12-14 15:48
Hi there,
I'm experiencing the same problem with the latest version of Lightly (1.2.39). However, when I ran the same script with my older version of Lightly, the problem didn't occur and there was no collapse. It looks like the issue was introduced in version 1.2.37 of Lightly (no collapse with 1.2.36), which suggests it may be related to the modification of the MemoryBankModule wich is also used by the Moco loss. I'm also having the same issue when running the [Lightly benchmark on Imagenette](https://docs.lightly.ai/self-supervised-learning/getting_started/benchmarks.html#imagenette) with Moco, with a loss also getting stuck at 8.32 after the first epoch.

**Comment by guarin** [comment] 2022-12-14 15:56
Hi, I can confirm that it works on 1.2.36 and not on 1.2.38. 
Looks like we introduced a bug, probably in #993. Will have a look as soon as possible.

**Comment by guarin** [comment] 2022-12-15 07:34
I think we found the problem. Should be fixed in the next release (v.1.2.40). Until then you can either use v1.2.36 or install lightly from the branch in PR #1009.

Thanks a lot for the bug report!

**Closed** 2022-12-15 08:41 UTC
