### ISSUE TITLE
complete example of NNCLR implementation

### ISSUE THREAD

**Issue by ramdhan1989** [lightly-ai/lightly#422] opened 2021-06-28 01:23 UTC
Hi,
is there complete tutorial to use NNCLR ? I see in [here](https://github.com/lightly-ai/lightly/issues/414) but seems need to be elaborated more.

thank you

**Comment by HBU-Lin-Li** [comment] 2021-06-28 02:40
Hi,
Now, have you got what are  x0 and x1 parameter in model(x0, x1) under forward pass comment?
I also have questions in here.

**Comment by philippmwirth** [comment] 2021-06-28 07:47
Dear @ramdhan1989 and @HBU-Lin-Li, since this is a duplicate of #414, I decided to re-open it and mark this issue as a duplicate.

Please refer to #414 for further discussions. Thanks!

**Closed by philippmwirth** 2021-06-28 07:47 UTC
Labels: status: duplicate
